### ISSUE TITLE
Testing on Chrome

### ISSUE THREAD

**Issue by sydneydowd** [shaayaanjameel/portfolio#1]
Logo doesn't line up with nav and images below

**Comment by norr0065** [comment]
Same as in Firefox

**Comment by bradley-doyle** [comment]
In Safari

Logo doesn't scale on different sized screens and becomes off centre (see photo)

![screen shot 2015-10-06 at 3 40 39 pm](https://cloud.githubusercontent.com/assets/4565418/10320273/a6874fb2-6c40-11e5-99c5-8136ca39a48f.png)

On android

the logo seems to be scaled but off centre and the spacing becomes very drastic from each section
